version: 0.0.{build}
configuration: Release
assembly_info:
  patch: true
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
before_build:
  - nuget restore
build:
  publish_nuget: false
  verbosity: minimal
